#Code generated by Chatgpt improving my original code

import SimpleITK as sitk
from pathlib import Path

input_dir = "in_plane"
output_file = "registered_stack.tif"

# Collect TIFF files
tiff_files = sorted(Path(input_dir).glob("*.tif"))

images = [sitk.ReadImage(str(f), sitk.sitkFloat32) for f in tiff_files]

registered_images = []
registered_images.append(images[0])  # first slice is reference

for i in range(1, len(images)):

    fixed = registered_images[-1]   # previous registered slice
    moving = images[i]

    # Normalize intensities
    fixed = sitk.Normalize(fixed)
    moving = sitk.Normalize(moving)

    registration = sitk.ImageRegistrationMethod()

    # Metric
    registration.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
    registration.SetMetricSamplingStrategy(registration.RANDOM)
    registration.SetMetricSamplingPercentage(0.2)

    # Interpolation
    registration.SetInterpolator(sitk.sitkLinear)

    # Optimizer
    registration.SetOptimizerAsGradientDescent(
        learningRate=0.5,
        numberOfIterations=300,
        convergenceMinimumValue=1e-6,
        convergenceWindowSize=10
    )

    # Multi-resolution pyramid
    registration.SetShrinkFactorsPerLevel([4,2,1])
    registration.SetSmoothingSigmasPerLevel([2,1,0])
    registration.SmoothingSigmasAreSpecifiedInPhysicalUnitsOn()

    # Transform
    initial_transform = sitk.CenteredTransformInitializer(
        fixed,
        moving,
        sitk.Euler2DTransform(),
        sitk.CenteredTransformInitializerFilter.GEOMETRY
    )

    registration.SetInitialTransform(initial_transform, inPlace=False)

    final_transform = registration.Execute(fixed, moving)

    # Resample moving image
    registered = sitk.Resample(
        moving,
        fixed,
        final_transform,
        sitk.sitkLinear,
        0.0,
        moving.GetPixelID()
    )

    registered_images.append(registered)

# Save stack
stack = sitk.JoinSeries(registered_images)

sitk.WriteImage(stack, output_file)
